name 'hpi_app'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures hpi_app'
long_description 'Installs/Configures hpi_app'
version '0.1.0'
